import "../../node_modules/tailwindcss/tailwind.css";
import Header from "@/src/components/fragments/Header";
import AppLayout from "@/src/components/layouts/AppLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col items-center w-full h-screen bg-retroWhite container-none">
          <Header />
          <AppLayout>{children}</AppLayout>
        </div>
      </body>
    </html>
  );
}
