import "./globals.css";
import Sidebar from "../components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <div className="container h-full w-full border border-red-500 mx-auto flex flex-col justify-between items-center">
          <div className="w-full flex justify-between items-center">
            <h1 className="text-3xl text-center font-semibold">
              NUMBER CONVERTION
            </h1>
            <p className="text-2xl">Ahmad Zaky Ubaidillah</p>
            <p className="text-xl">112210010</p>
          </div>
          <div className="h-full w-full mx-auto flex justify-between items-center">
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
